[package]
name = "data-processor"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3"
data = { path = "../data" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
xz2 = "0.1"
