[package]
name = "dos-helper"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3"
data = { path = "data" }
lzma-rs = "0.2"
seed = "0.8"
serde = "1.0"

[workspace]
members = ["data", "data-processor"]
